services:
  - type: web
    name: multiplic-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7 